version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 4
    labels:
      - "automated pr"
    groups:
      # Astro core + Starlight & plugins together
      astro-starlight:
        patterns:
          - "astro"
          - "@astrojs/*"
          - "astro-*"
          - "starlight-*"
        update-types:
          - "minor"
          - "patch"
      # Everything else npm
      npm-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "astro"
          - "@astrojs/*"
          - "astro-*"
          - "starlight-*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 4
    labels:
      - "automated pr"
    groups:
      github-actions:
        patterns:
          - "*"
