name: "Documentation issue"
description: Report a problem with documentation.
body:
  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: The link to the page this issue is about or, if it's about multiple pages, an example or most important page.
    validations:
      required: true
  - type: input
    id: section
    attributes:
      label: What specific section or headline is this issue about?
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, steps to reproduce a bug, screenshots, screen recordings, or sample code
